-- 코드를 입력하세요
SELECT CART_ID
FROM
(SELECT DISTINCT CART_ID, NAME
FROM CART_PRODUCTS
WHERE NAME = "MILK"
UNION
SELECT DISTINCT CART_ID, NAME
FROM CART_PRODUCTS
WHERE NAME = "Yogurt") AS CART
GROUP BY CART.CART_ID
HAVING COUNT(NAME) = 2
