-- 코드를 입력하세요
-- 자동차 종류 : 세단 SUV
-- 2022년 11월 1일~11월 30일 대여 가능
-- 30일 대여 금액 50~200
SELECT 
    C.CAR_ID AS CAR_ID, 
    C.CAR_TYPE AS CAR_TYPE, 
    ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C 
JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE 
    C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
    ) 
    AND P.DURATION_TYPE LIKE '30%' 
    AND C.CAR_TYPE IN ('세단', 'SUV') 
GROUP BY 
    C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, P.DISCOUNT_RATE
HAVING 
    FEE >= 50000 AND FEE < 2000000
ORDER BY 
    FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;
