-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', IFNULL(STREET_ADDRESS2, '')) as 전체주소, CONCAT(SUBSTR(U.TLNO, 1, 3),'-',SUBSTR(U.TLNO,4,4),'-',SUBSTR(U.TLNO,8,4)) as 전화번호
FROM USED_GOODS_USER U 
JOIN (SELECT WRITER_ID
     FROM USED_GOODS_BOARD
     GROUP BY WRITER_ID
     HAVING count(*) >=3) B ON U.USER_ID = B.WRITER_ID
ORDER BY U.USER_ID DESC