SELECT T.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (SELECT A.ITEM_ID
                           FROM ITEM_INFO A INNER JOIN ITEM_TREE B
                           ON A.ITEM_ID = B.ITEM_ID
                           WHERE A.RARITY LIKE 'RARE')
ORDER BY T.ITEM_ID DESC
        